{
 "title": "Smoking",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Probe Temperatures (°F)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Ch1\")\n  |> keep(columns:FinalOutput)"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Ch2\")\n  |> keep(columns:FinalOutput)"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Ch3\")\n  |> keep(columns:FinalOutput)"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Ch4\")\n  |> keep(columns:FinalOutput)"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Ch5\")\n  |> keep(columns:FinalOutput)"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Ch6\")\n  |> keep(columns:FinalOutput)"
    },
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"weathergov\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weathergov\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_dewpoint_value\")\n    |> map(fn: (r) => ({\n      r with\n      _value: (r._value * 9.0/5.0) + 32.0\n      })\n   )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Dewpoint\")\n  |> keep(columns:FinalOutput)\n  |> yield(name: \"mean\")  "
    }
   ]
  },
  {
   "title": "Temp (°F)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weathergov\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weathergov\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_temperature_value\")\n  |> map(fn: (r) => ({\n      r with\n      _value: (r._value * 9.0/5.0) + 32.0\n      })\n   )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dew Point (°F)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weathergov\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weathergov\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_dewpoint_value\")\n    |> map(fn: (r) => ({\n      r with\n      _value: (r._value * 9.0/5.0) + 32.0\n      })\n   )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")  "
    }
   ]
  },
  {
   "title": "Probe 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Probe1\")\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Probe 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Probe2\")\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Probe 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Probe3\")\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Probe 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Probe4\")\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Probe 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Probe5\")\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Probe 6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"fireboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"channel\"] == \"6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"Probe6\")\n  |> keep(columns:FinalOutput)"
    }
   ]
  },
  {
   "title": "Temp and Dew Point (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\nfrom(bucket: \"weathergov\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weathergov\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_temperature_value\" or r[\"_field\"] == \"properties_dewpoint_value\" or r[\"_field\"] == \"properties_heatIndex_value\")\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field == \"properties_dewpoint_value\" then \"Dewpoint\"\n          else if r._field == \"properties_heatIndex_value\" then \"Heat Index\"\n          else \"Temperature\"\n        })\n      )\n  |> keep(columns:FinalOutput)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  }
 ]
}